version: '3.3'
services:

  # -------------------- Indy agents -----------------------
  agent94:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
#    network_mode: host
    ports:
      - "8094:8094"
    environment:
      - "PORT=8094"
    container_name: agent94

  agent95:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
#    network_mode: host
    ports:
      - "8095:8095"
    environment:
      - "PORT=8095"
    container_name: agent95

  agent96:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
#    network_mode: host
    ports:
      - "8096:8096"
    environment:
      - "PORT=8096"
    container_name: agent96

  agent97:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
    #    network_mode: host
    ports:
      - "8097:8097"
    environment:
      - "PORT=8097"
    container_name: agent97

  agentInitiator:
    image: alpine:3.6
    network_mode: host
    container_name: agentInitiator
    depends_on:
      - agent94
      - agent95
      - agent96
      - agent97
    command: sh -c 'sleep 10; /usr/bin/wget --spider http://localhost:8094/; /usr/bin/wget --spider http://localhost:8095/; /usr/bin/wget --spider http://localhost:8096/; /usr/bin/wget --spider http://localhost:8097/'
